-- ============================================
-- CONFIGURACIÓN DE BRANDING PARA GOOGLE OAUTH
-- ============================================
-- 
-- IMPORTANTE: Este archivo NO contiene SQL ejecutable.
-- Son instrucciones para configurar manualmente el branding
-- de Google OAuth en Google Cloud Console.
--
-- Para que la pantalla de autenticación de Google muestre
-- "Terreta Hub" y el logo en lugar del dominio de Supabase,
-- sigue estos pasos:
--
-- ============================================
-- PASO 1: ACCEDER A GOOGLE CLOUD CONSOLE
-- ============================================
-- 1. Ve a https://console.cloud.google.com/
-- 2. Selecciona el proyecto asociado a tu aplicación Supabase
-- 3. Si no tienes un proyecto, créalo primero
--
-- ============================================
-- PASO 2: CONFIGURAR PANTALLA DE CONSENTIMIENTO
-- ============================================
-- 1. Ve a: APIs & Services > OAuth consent screen
-- 2. Selecciona el tipo: External (público) o Internal (solo organización)
--
-- ============================================
-- PASO 3: COMPLETAR INFORMACIÓN DE LA APP
-- ============================================
-- App name: Terreta Hub
-- User support email: [tu-email-de-soporte]
-- App logo: Sube public/logo.png
--   - Formato: PNG, JPG o GIF
--   - Tamaño máximo: 1 MB
--   - Dimensiones mínimas: 200x200 píxeles
--
-- Developer contact information: [tu-email]
--
-- ============================================
-- PASO 4: CONFIGURAR SCOPES
-- ============================================
-- Agregar los siguientes scopes:
--   - email
--   - profile
--   - openid
--
-- ============================================
-- PASO 5: AGREGAR DOMINIOS AUTORIZADOS
-- ============================================
-- En "Authorized domains", agregar:
--   - terretahub.com
--   - [tu-proyecto].supabase.co
--
-- ============================================
-- PASO 6: VERIFICAR LA MARCA (OPCIONAL)
-- ============================================
-- Google requiere verificación de marca para aplicaciones externas.
-- Este proceso puede tardar varios días hábiles.
-- Sigue las instrucciones en la consola para completar la verificación.
--
-- ============================================
-- PASO 7: CONFIGURAR CREDENCIALES OAUTH
-- ============================================
-- 1. Ve a: APIs & Services > Credentials
-- 2. Crea un nuevo "OAuth 2.0 Client ID":
--    - Application type: Web application
--    - Name: Terreta Hub OAuth
--    - Authorized redirect URIs:
--      https://[tu-proyecto-supabase].supabase.co/auth/v1/callback
--
-- ============================================
-- PASO 8: CONFIGURAR EN SUPABASE DASHBOARD
-- ============================================
-- 1. Ve a: https://supabase.com/dashboard
-- 2. Navega a: Authentication > Providers
-- 3. Activa: Google
-- 4. Ingresa:
--    - Client ID: [copiado de Google Cloud Console]
--    - Client Secret: [copiado de Google Cloud Console]
-- 5. Guarda los cambios
--
-- ============================================
-- RESULTADO ESPERADO
-- ============================================
-- Después de completar estos pasos:
-- - Los usuarios verán "Terreta Hub" como nombre de la app
-- - Verán el logo de Terreta Hub
-- - En lugar de mostrar solo el dominio de Supabase,
--   mostrará información de Terreta Hub
--
-- ============================================
-- NOTAS IMPORTANTES
-- ============================================
-- - La verificación de marca puede tardar varios días
-- - Mientras tanto, Google puede mostrar una advertencia
-- - Una vez verificada, la experiencia será completamente personalizada
-- - El logo debe cumplir con los requisitos de Google
--
-- ============================================
-- TROUBLESHOOTING
-- ============================================
-- Si después de configurar todo aún no se muestra el branding:
-- 1. Verifica que el logo cumpla con los requisitos
-- 2. Espera 24-48 horas para que los cambios se propaguen
-- 3. Verifica que las credenciales OAuth estén correctas en Supabase
-- 4. Asegúrate de que el dominio esté autorizado en Google Cloud Console
--
-- ============================================
-- FIN DE INSTRUCCIONES
-- ============================================
